### ISSUE TITLE
Doesn't work on Gnome 40 Wayland.

### ISSUE THREAD

**Issue by chdslv** [jdoda/hotedge#1]
Doesn't work on Gnome 40 Wayland. When this extension is enabled, there's no hotcorner/hot edge at all.

**Comment by jdoda** [comment]
Thanks for the bug report! I'm sorry the extension isn't working for you. The extension was developed on a system running Wayland, so that shouldn't be the problem, but if you can share more information hopefully we can figure it out.

First off, can you run `journalctl -g hotedge /usr/bin/gnome-shell` and paste any results? 

Second, if you can answer the following questions it would be a big help:

- What distribution and distribution version are you running?
- Are you running on a VM or on bare metal? If a VM, how are you running it (e.g. GNOME Boxes, qemu, VirtualBox, etc)?
- What graphics hardware are you using, and what driver are you using for it?
- What's your monitor layout?

**Comment by rdiezsj** [comment]
I have same issue.
```
$ journalctl -g hotedge /usr/bin/gnome-shell
-- Journal begins at Wed 2021-04-28 00:22:49 CEST, ends at Wed 2021-04-28 02:30:50 CEST. --
-- Boot 4fcd585b5cfe4329b3209780e6eb7f5e --
-- Boot 933bf0aead924dee81e88e508d1c0cc2 --
-- Boot 45eadf67e98f47dcaf30cac1132cd871 --
-- No entries --
```

- Fedora 34
- Bare metal
- amd rx5600xt
- all default

**Comment by jdoda** [comment]
Thanks for the info! Unfortunately your setup is very similar to the machine I'm developing on, so that doesn't really provide any clues as to what's happening. I'm going to upload a new version with more logging, and see if that turns up anything. I'll update the issue when that version is available.

**Comment by jdoda** [comment]
Ok, the new version is active on the extensions site now. If you can go to https://extensions.gnome.org/extension/4222/hot-edge/ and update your version of the extension (and then log out and in again, I think) and then report back the output from `journalctl -g hotedge /usr/bin/gnome-shell` that would be a huge help!

**Comment by rdiezsj** [comment]
After update, seems to be working :)
```
$ journalctl -g hotedge /usr/bin/gnome-shell
-- Journal begins at Wed 2021-04-28 00:22:49 CEST, ends at Wed 2021-04-28 03:41:51 CEST. --
-- Boot 4fcd585b5cfe4329b3209780e6eb7f5e --
-- Boot 933bf0aead924dee81e88e508d1c0cc2 --
-- Boot 45eadf67e98f47dcaf30cac1132cd871 --
-- Boot 92b0d429f9e24be1b08899804949c9a0 --
abr 28 03:41:44 rzn-fedora gnome-shell[3458]: HotEdge: Updating hot edges.
abr 28 03:41:44 rzn-fedora gnome-shell[3458]: HotEdge: Monitor 0 has a bottom, adding a hot edge.
abr 28 03:41:44 rzn-fedora gnome-shell[3458]: HotEdge: Creating hot edge x: 0 y: 1440
abr 28 03:41:44 rzn-fedora gnome-shell[3458]: HotEdge: Setting barrier size to 2560

```

**Comment by jdoda** [comment]
Good grief. Well, I'm happy it's working at least.

**Comment by jdoda** [comment]
Hey @chdslv, are you still experiencing problems using the extension? There have been some updates to the extension since you opened this issue that may help, but if you are still having problems I won't be able to diagnose them without more information.  Just to keep things tidy, if you don't respond in the next week I'm going to close this issue.

**Comment by chdslv** [comment]
Sorry about not responding before. I needed only one thing, that is to get the top left hotcorner to bottom left, which I got working another way, so you can close this issue. Regards!
