### ISSUE TITLE
Disable Hot Edge if Activity View is already open

### ISSUE THREAD

**Issue by Noremacam** [jdoda/hotedge#10]
This is a feature request.

I would like to have the hot edge disabled if activity view is already open. When I open the activity view with the Super key, I don't want to accidentally close the view when moving the mouse to the bottom of the screen to select an application. 

This could be a toggle if undesired by others.

Thanks for the consideration.

**Comment by jdoda** [comment]
Thanks for opening an issue! I'm sorry to disappoint, but I've given it some thought and I'm not going to implement this behaviour, for two reasons: First, I find that I actually intentionally close the overview with the hot edge fairly often (I spend a lot of time working on a smallish laptop screen, so sometimes I just open the overview to peek at what's going on in a background window). Second, it's important that opening the overview is an easily reversible operation. Currently you can close the overview simply by repeating whatever action you used to open it and for new users especially that's a very useful behaviour, since it helps prevent you from getting trapped in the overview.

Neither of these reasons preclude me from adding an option to turn on this behaviour, but as a rule I'm disinclined to add options that I won't use and that require new code, since that code would go largely untested.

All that said, if you find that you're accidentally triggering the hot edge enough for it to be a problem, you may want to increase the required activation pressure. There's already an option for that, which you can adjust from a terminal like so: `gsettings --schemadir ~/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas set org.gnome.shell.extensions.hotedge pressure-threshold 200` (where the 200 can be any number you want, with higher numbers requiring more pressure to activate the edge).
