### ISSUE TITLE
Trigger the overview when an application is in full screen mode

### ISSUE THREAD

**Issue by dmarrazzo** [jdoda/hotedge#12]
Maybe it could be an option, but I'd like to have the hot edge even when an application is in full screen mode.

**Comment by jdoda** [comment]
This is behaviour inherited from the existing hot corner code. It's an explicit check that suppresses toggling the overview if there's a fullscreen app. Because it is an explicit check, it should be easy to change this behaviour, but it also means it's probably there for a reason. I'll do some testing and see if removing it breaks anything.

**Comment by jdoda** [comment]
Having put some more thought into this, I don't want to diverge from the hot corner behaviour here.
