### ISSUE TITLE
Hot edge broken since last update on Fedora 36

### ISSUE THREAD

**Issue by Af0x** [jdoda/hotedge#18]
Hello, since the last update it seems the Hot Edge Extension is broken on my Fedora 36 machine. Best regards

**Comment by jdoda** [comment]
Hey, sorry you're having trouble, and thanks for getting in touch. 

If you can provide the output of running the command `journalctl -g hotedge -r` in the terminal that would help debugging. It's probably also worth logging out and back in again, or restarting your computer. There were no code changes in the last update, so there's no reason Hot Edge shouldn't be working now if it was working before, but I have noticed in the past that the extension update mechanism can be a bit flaky. If that's the problem, logging out and in or restarting should fix the problem.

**Comment by Af0x** [comment]
I removed and reinstalled the extension already and after a restart it works again. That being said I can´t reproduce it again as it might have been an update issue. Thanks for your work & best regards

**Comment by msergein** [comment]
hello, I have the same problem, I didn't try to reboot.
The output of `journalctl -g hotedge -r`
```
сен 07 00:57:21 fedora gnome-shell[2975]: JS ERROR: Extension hotedge@jonathan.jdoda.ca: Error: A different version was loaded previously. You need to log out for change>
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:374:52
                                             _onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:267:35
                                             Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41
сен 07 00:57:21 fedora gnome-shell[131828]:  extracting: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/metadata.json
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/extension.js
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/prefs.js
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/stylesheet.css
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/logger.js
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas/gschemas.compiled
сен 07 00:57:21 fedora gnome-shell[131828]:   inflating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas/org.gnome.shell.extensions.ho>
сен 07 00:57:21 fedora gnome-shell[131828]:    creating: /home/sergey/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas/
сен 07 00:56:44 fedora gnome-shell[2975]: HotEdge | INFO | Updating hot edges.
```

**Comment by msergein** [comment]
after uninstalling the extension, rebooting and fresh installation everything really works
thanks for the great extension

**Comment by jdoda** [comment]
Thanks for the logs @msergein . It definitely narrows it down to a problem (?) with the extension update mechanism in GNOME Shell. I had a look at the code where the error is emitted ( https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/extensionSystem.js#L375 ) but unfortunately I can't quite work out what's going on there. It looks like there's a check we're hitting that prevents you from loading an extension if a different version of the same extension had been loaded at some previous point in the current session. That's fair enough, but it doesn't really explain why it unloads the previous version when it should know the new version can't be loaded yet. Just from experience, it also doesn't seem to be the case that updating an extension always unloads the previous version. Usually it seems like it just updates whenever you log in the next time, and until then it happily keeps running the old version.

Unfortunately I don't have much time to look into this, and since the problem can be fixed by logging out and logging back in, it's not a high priority at the moment. Thanks for opening the issue, though. If this becomes a larger issue in the future it will be helpful to have this research as a starting point.
