### ISSUE TITLE
[Feature Request] Allow changing of activation 'Edge' 

### ISSUE THREAD

**Issue by seanleavy** [jdoda/hotedge#20]
Hi. thanks for the great extension

Proposal:
Create a setting to pick which edge is the active one ie. **top**, **bottom,** **left,** **right**

Use Case;
Overview dock moved to a different edge of the screen. Ex: 'Vertical Overview' extension moves the dock on the left side in overview

Rgds

**Comment by jdoda** [comment]
Thanks for the feedback! 

I've given this some thought, but I'm sorry to say that not going to implement this feature. There's a lot of logic that's determined by what side of the screen the edge will be on, and making that logic generic for any side will increase the complexity of the code by a fair amount. It's also hard to imagine a use case beyond putting the edge on the left side because you're using a vertical overview extension, and in that case I think the existing hot corner probably works well enough for most people. All that said, I think it's probably possible to set-up a left side hot edge using this extension:  https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/ so you might give that a try.

Thanks again for reaching out, and sorry again that I couldn't directly accommodate your request.
