### ISSUE TITLE
Edge size automation, feature request

### ISSUE THREAD

**Issue by ghabit** [jdoda/hotedge#23]
We have edge size options - percentage part of active screen - is it possible to automate this according to dash size? It enlarges and shrinks while system using.

**Comment by ghabit** [comment]
UPD: this https://github.com/fthx/dock-from-dash extension have this feature working by default, maybe it can help.

**Comment by jdoda** [comment]
Thanks for the suggestion and sorry for the delay in responding, I was taking a bit of a break. 

I've considered this idea, but I'm not going to implement it. The user can't see the size of the dash when they're not in the overview, and so if the size of the hot edge is set by the size of the dash, the user will never be entirely certain where they have to put the mouse in order to activate the hot edge. I think it's important to the usability of the hot edge that it always be in the same location and have the same size.
