### ISSUE TITLE
[feature request]  Configurable screen edge

### ISSUE THREAD

**Issue by eode** [jdoda/hotedge#31]
It's pretty much all in the title -- It would be nice to be able to choose which edge is hot.

**Comment by jdoda** [comment]
I'm keeping the extension intentionally minimal so that maintaining it isn't too much of a burden, so while this could be a useful feature, I'm not going to add it. If you're looking for something more customizable, https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/ may be worth looking at.
