### ISSUE TITLE
RFE: avoiding corners

### ISSUE THREAD

**Issue by juhp** [jdoda/hotedge#7]
Thanks for this cool extension, pretty neat.

I have a suggestion I feel could increase the usability even more:
at least an option/setting to avoid (ignore) triggering in the corners of the hot edge.

eg if I drag down my browser's scrollbar hard I will almost certainly trigger the overview, which is probably not what I want.

If HotEdge only triggered more towards the edge centre that would be much better I feel.
If necessary it could be configurable by a percentage say: 100 would mean use the full edge,
though I feel a default of around 60-80% might be ideal. How do you think?

**Comment by jdoda** [comment]
Thanks for opening an issue, that's an interesting idea. While it is important to avoid accidental activations, I'm worried this approach would cause too many accidental _non-activiations_, and that on balance it would make the extension feel less predictable and reliable. Particularly since the extent of the hot portion of the bottom edge wouldn't be visible to the user, they may have a hard time understanding why the edge isn't activating. In any case, it probably is worth a try, so I'll experiment with it a bit and see how it feels in practice.

If you're currently experiencing an annoying number of accidental activations, though, there might be other solutions. First it would be worth knowing if you're using the pressure-based activation code or the fallback code. If you run the command `journalctl -g hotedge /usr/bin/gnome-shell` and see a line like `Display does not support extended barriers, falling back to old method.` that means you're using the fallback code, which is much more prone to accidental activation (unfortunately since I'm not really certain what causes extended barriers to not be supported on a system, I don't know what you can do about this).

If you're not using the fallback code and you're experiencing accidental activations, it may be worth tuning the activation pressure. The [README](https://github.com/jdoda/hotedge/blob/main/README.md) has the details, but to sum up you can change the pressure from e.g. the default 100 pixels to 200 pixels using this command `gsettings --schemadir ~/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas set org.gnome.shell.extensions.hotedge pressure-threshold 200`.

**Comment by juhp** [comment]
Thanks

So far I have only accidentally activated when dragging down the scrollbar (eg for a log webpage),
which I don't do so frequently.

I think I have extended barriers (Wayland on T480s), though I couldn't get your extension to work in a windowed VM (virt-manager); anyway I only really need it for real in my host desktop.

**Comment by jdoda** [comment]
Ok, I've added a corner deadzone feature to the latest version, which is available now. You can activate it using gsettings, e.g. `gsettings --schemadir ~/.local/share/gnome-shell/extensions/hotedge@jonathan.jdoda.ca/schemas set org.gnome.shell.extensions.hotedge corner-deadzone 24` would set a deadzone of 24 pixels at each corner.

**Comment by juhp** [comment]
Cool, thanks a lot!

**Comment by juhp** [comment]
I tested it - it seems to work great!!

**Comment by sfllaw** [comment]
As a follow up to this request, dead zones in the corners seems like a terrible hack.

I wonder if it would be better to ignore the Hot Edge of a nose button is being held down? I know of no instance where holding down a mouse button is useful, and the default Hot Corner ignores this case.

The default behavior will be intuitively correct for the original feature request and there won't be strange dead zones.

**Comment by jdoda** [comment]
Thanks for the report. The hot edge is supposed to work the same way as the hot corner with regards to drags (i.e. it shouldn't trigger if a mouse button is held down) but it looks like that's broken on Wayland (oddly, it works correctly under Xorg). I'll have to figure out how I broke it and make a change. I'll open a new issue for this fix.
